import { AppShell } from "@/components/AppShell";
import { createClient } from "@/lib/supabase/server";
import { EvidenceTag } from "@/components/EvidenceTag";

export default async function ProfessorDossierPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const supabase = await createClient();

  const { data: prof } = await supabase
    .from("professors")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (!prof) {
    return (
      <AppShell>
        <p className="text-sm text-slate-600">Professor not found.</p>
      </AppShell>
    );
  }

  const [{ data: affils }, { data: sources }, { data: metrics }, { data: labMembers }] =
    await Promise.all([
      supabase
        .from("professor_affiliations")
        .select("title, schools(name), departments(name, abbrev)")
        .eq("professor_id", id),
      supabase
        .from("professor_sources")
        .select("source_type, source_url, retrieved_at, confidence")
        .eq("professor_id", id)
        .order("confidence", { ascending: false }),
      supabase
        .from("professor_metrics")
        .select("citation_count, h_index, works_count, as_of")
        .eq("professor_id", id)
        .order("as_of", { ascending: false })
        .maybeSingle(),
      supabase.from("lab_members").select("name, role, research_note").eq("professor_id", id),
    ]);

  const avgConfidence =
    (sources ?? []).reduce((s, r) => s + Number(r.confidence), 0) /
    Math.max(1, (sources ?? []).length);
  const lastUpdated = sources?.[0]?.retrieved_at;

  return (
    <AppShell>
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-brand">{prof.full_name}</h1>
          <p className="mt-1 text-slate-600">{prof.research_identity}</p>
        </div>
        <div className="text-right text-xs text-slate-500">
          <p>Source confidence: {(avgConfidence * 100).toFixed(0)}%</p>
          {lastUpdated && <p>Updated: {new Date(lastUpdated).toLocaleDateString()}</p>}
        </div>
      </div>

      {prof.full_name?.includes("[SAMPLE]") && (
        <div className="card mt-4 border-amber-200 bg-amber-50 text-sm text-amber-800">
          This is synthetic seed data for development. Do not use for real applications.
        </div>
      )}

      <div className="mt-6 grid gap-6 md:grid-cols-3">
        <div className="md:col-span-2 space-y-6">
          <section className="card">
            <h2 className="font-semibold">Affiliation & departments</h2>
            <ul className="mt-2 text-sm text-slate-700">
              {(affils ?? []).map((a: any, i) => (
                <li key={i}>
                  {a.title} · {a.schools?.name} — {a.departments?.name} ({a.departments?.abbrev})
                  <EvidenceTag kind="verified_fact" />
                </li>
              ))}
            </ul>
          </section>

          <section className="card">
            <h2 className="font-semibold">Research themes</h2>
            <div className="mt-2 flex flex-wrap gap-2">
              {(prof.research_themes ?? []).map((t: string) => (
                <span key={t} className="rounded-full bg-slate-100 px-2 py-0.5 text-xs">
                  {t}
                </span>
              ))}
            </div>
          </section>

          <section className="card">
            <h2 className="font-semibold">Lab members & projects</h2>
            {labMembers?.length ? (
              <ul className="mt-2 space-y-1 text-sm">
                {labMembers.map((m, i) => (
                  <li key={i}>
                    <span className="font-medium">{m.name}</span> — {m.role}: {m.research_note}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="mt-2 text-sm text-slate-400">
                <EvidenceTag kind="missing_uncertain" /> Lab roster not yet retrieved.
              </p>
            )}
          </section>

          <section className="card">
            <h2 className="font-semibold">Application strategy</h2>
            <p className="mt-2 text-sm text-slate-600">
              <EvidenceTag kind="inferred_fit" /> Generated by the Story Coach during the Story
              Builder step. Talking points and papers-to-read appear there once you save this
              professor to your shortlist.
            </p>
          </section>
        </div>

        <aside className="space-y-6">
          <section className="card">
            <h2 className="font-semibold">Bibliometrics</h2>
            {metrics ? (
              <ul className="mt-2 text-sm text-slate-700">
                <li>Citations: {metrics.citation_count?.toLocaleString() ?? "—"}</li>
                <li>h-index: {metrics.h_index ?? "—"}</li>
                <li>Works: {metrics.works_count ?? "—"}</li>
              </ul>
            ) : (
              <p className="mt-2 text-sm text-slate-400">
                <EvidenceTag kind="missing_uncertain" /> No metrics retrieved yet.
              </p>
            )}
          </section>

          <section className="card">
            <h2 className="font-semibold">Sources</h2>
            <ul className="mt-2 space-y-2 text-xs">
              {(sources ?? []).map((s, i) => (
                <li key={i}>
                  <span className="font-medium">{s.source_type}</span>{" "}
                  ({(Number(s.confidence) * 100).toFixed(0)}%)
                  {s.source_url && (
                    <>
                      {" · "}
                      <a href={s.source_url} className="text-brand-accent underline" target="_blank" rel="noreferrer">
                        link
                      </a>
                    </>
                  )}
                  <br />
                  <span className="text-slate-400">
                    {new Date(s.retrieved_at).toLocaleDateString()}
                  </span>
                </li>
              ))}
              {(!sources || sources.length === 0) && (
                <li className="text-slate-400">No source records.</li>
              )}
            </ul>
          </section>
        </aside>
      </div>
    </AppShell>
  );
}
